# options.zsh — Zsh shell options

# History
setopt HIST_EXPIRE_DUPS_FIRST HIST_IGNORE_DUPS HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE HIST_SAVE_NO_DUPS HIST_REDUCE_BLANKS HIST_VERIFY
setopt SHARE_HISTORY APPEND_HISTORY INC_APPEND_HISTORY EXTENDED_HISTORY

# Navigation
setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS PUSHD_MINUS CDABLE_VARS

# Completion
setopt AUTO_MENU ALWAYS_TO_END COMPLETE_IN_WORD
setopt HASH_LIST_ALL LIST_AMBIGUOUS

# Globbing
setopt EXTENDED_GLOB GLOB_DOTS NUMERIC_GLOB_SORT NOMATCH

# Interaction
setopt INTERACTIVE_COMMENTS LONG_LIST_JOBS NOTIFY
setopt NO_BG_NICE NO_HUP NO_CHECK_JOBS
setopt NO_BEEP PROMPT_SUBST AUTO_RESUME
# CORRECT is noisy; leave off by default. Enable in .zshrc.local if desired.
