[font]
normal      = { family = "Cascadia Code NF", style = "Light" }
bold        = { family = "Cascadia Code NF", style = "Bold" }
italic      = { family = "Cascadia Code NF", style = "Light Italic" }
bold_italic = { family = "Cascadia Code NF", style = "Bold Italic" }
