# managed.sh — append/remove managed configuration blocks
# shellcheck shell=sh
#
# Used when --append is set (or as a safe alternative to full symlinks).
# Markers defined in common.sh:
#   DOTFILES_MANAGED_BEGIN / DOTFILES_MANAGED_END
#
# Note: POSIX sh has no local variables. Each function uses a unique prefix
# so nested calls never clobber the caller's state.

# Return 0 if file already contains a managed block.
df_has_managed_block() {
    _df_hmb_file=$1
    if [ ! -f "$_df_hmb_file" ]; then
        return 1
    fi
    grep -qF "$DOTFILES_MANAGED_BEGIN" "$_df_hmb_file" 2>/dev/null
}

# Remove an existing managed block from a file (idempotent).
df_remove_managed_block() {
    _df_rmb_file=$1
    if [ ! -f "$_df_rmb_file" ]; then
        return 0
    fi
    if ! df_has_managed_block "$_df_rmb_file"; then
        return 0
    fi

    if [ "$DOTFILES_DRY_RUN" = "1" ]; then
        log_dry "Would remove managed block from $_df_rmb_file"
        return 0
    fi

    _df_rmb_tmp="${_df_rmb_file}.dotfiles.tmp"
    # Delete lines from BEGIN through END inclusive.
    awk -v b="$DOTFILES_MANAGED_BEGIN" -v e="$DOTFILES_MANAGED_END" '
        $0 == b { skip=1; next }
        $0 == e { skip=0; next }
        !skip { print }
    ' "$_df_rmb_file" >"$_df_rmb_tmp" && mv "$_df_rmb_tmp" "$_df_rmb_file"
    _df_rmb_rc=$?
    rm -f "$_df_rmb_tmp" 2>/dev/null || true
    log_verbose "Removed managed block from $_df_rmb_file"
    return $_df_rmb_rc
}

# Append a managed block that sources a given file.
# Usage: df_append_managed_source <target_rc> <file_to_source> [comment]
df_append_managed_source() {
    _df_ams_target=$1
    _df_ams_source=$2
    _df_ams_comment=${3:-dotfiles}

    # In dry-run the loader may not exist yet; still report the planned action.
    if [ "$DOTFILES_DRY_RUN" != "1" ] && [ ! -e "$_df_ams_source" ]; then
        log_error "Managed source missing: $_df_ams_source"
        return 1
    fi

    if [ -f "$_df_ams_target" ] && df_has_managed_block "$_df_ams_target"; then
        log_info "Managed block already present in $_df_ams_target (idempotent)"
        # Refresh contents: remove + re-add so source path stays current.
        if [ "$DOTFILES_FORCE" = "1" ]; then
            df_remove_managed_block "$_df_ams_target" || true
        else
            return 0
        fi
    fi

    if [ "$DOTFILES_DRY_RUN" = "1" ]; then
        log_dry "Would append managed block to $_df_ams_target sourcing $_df_ams_source"
        return 0
    fi

    # Create file if missing.
    if [ ! -e "$_df_ams_target" ]; then
        _df_ams_parent=$(dirname "$_df_ams_target")
        [ -d "$_df_ams_parent" ] || mkdir -p "$_df_ams_parent"
        : >"$_df_ams_target"
    fi

    {
        printf '\n%s\n' "$DOTFILES_MANAGED_BEGIN"
        printf '# %s — managed by dotfiles installer v%s\n' "$_df_ams_comment" "$DOTFILES_INSTALLER_VERSION"
        printf '# shellcheck source=/dev/null\n'
        printf '[ -r "%s" ] && . "%s"\n' "$_df_ams_source" "$_df_ams_source"
        printf '%s\n' "$DOTFILES_MANAGED_END"
    } >>"$_df_ams_target"

    df_journal_record "managed_block|${_df_ams_target}"
    printf '%s\n' "$_df_ams_target" >>"${DOTFILES_STATE_DIR}/managed.list"
    log_success "Appended managed block -> $_df_ams_target"
    return 0
}

# Build a small loader script that sources our shell config (append mode helper).
df_write_loader() {
    _df_wl_path=$1
    _df_wl_shell=$2

    if [ "$DOTFILES_DRY_RUN" = "1" ]; then
        log_dry "Would write loader $_df_wl_path for $_df_wl_shell"
        return 0
    fi

    _df_wl_parent=$(dirname "$_df_wl_path")
    [ -d "$_df_wl_parent" ] || mkdir -p "$_df_wl_parent"

    case "$_df_wl_shell" in
        zsh)
            cat >"$_df_wl_path" <<EOF
# Generated by dotfiles installer — do not edit
# Loads Zsh configuration from the dotfiles repository.
export DOTFILES_DIR="${DOTFILES_ROOT}"
[ -r "${DOTFILES_ROOT}/config/shell/zsh/.zshrc" ] && . "${DOTFILES_ROOT}/config/shell/zsh/.zshrc"
EOF
            ;;
        bash)
            cat >"$_df_wl_path" <<EOF
# Generated by dotfiles installer — do not edit
# Loads Bash configuration from the dotfiles repository.
export DOTFILES_DIR="${DOTFILES_ROOT}"
[ -r "${DOTFILES_ROOT}/config/shell/bash/.bashrc" ] && . "${DOTFILES_ROOT}/config/shell/bash/.bashrc"
EOF
            ;;
        sh)
            cat >"$_df_wl_path" <<EOF
# Generated by dotfiles installer — do not edit
# Loads POSIX sh configuration from the dotfiles repository.
export DOTFILES_DIR="${DOTFILES_ROOT}"
[ -r "${DOTFILES_ROOT}/config/shell/sh/.profile" ] && . "${DOTFILES_ROOT}/config/shell/sh/.profile"
EOF
            ;;
        *)
            log_error "Unknown shell for loader: $_df_wl_shell"
            return 1
            ;;
    esac

    df_journal_record "copy|${_df_wl_path}|generated"
    log_verbose "Wrote loader: $_df_wl_path"
    return 0
}
